CREATE OR REPLACE TRIGGER  TR_EXAM
    BEFORE INSERT ON EMP   -- INSERT 발생 선
    AFTER INSERT ON EMP    -- INSERT 발생 후
    INSTEAD OF INSERT ON EMP -- INSERT 대신 수행
    INSERT OR DELETE OR UPDATE  ON EMP  -- INSERT, UPEDATE, DELETE 모두 수행
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
     /*
       트리거 내용을 작성
     */
end;